title: Doc Detective
description: Doc Detective concepts, guides, and other content.
theme: just-the-docs
url: https://doc-detective.github.io

github_username: doc-detective

enable_copy_code_button: true

mermaid:
  version: "9.1.3"

callouts:
  warning:
    title: Warning
    color: red
  highlight:
    color: yellow
  note:
    title: Note
    color: purple

