name: Update doc-detective-common version

on:
  repository_dispatch:
    types:
      - update-common-package-event
  workflow_dispatch:
    inputs:
      version:
        description: 'The doc-detective-common version.'
        required: false

jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install specific version of doc-detective-common
      run: |
        npm install doc-detective-common@${{ github.event.client_payload.version || github.event.inputs.version }}

    - name: Regenerate references
      run: npm i

    - uses: stefanzweifel/git-auto-commit-action@v4
